/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_test_r_op1;
  wire [8-1:0] M_test_r_op2;
  wire [8-1:0] M_test_out;
  wire [1-1:0] M_test_zOut;
  wire [1-1:0] M_test_vOut;
  wire [1-1:0] M_test_nOut;
  wire [28-1:0] M_test_text;
  reg [5-1:0] M_test_io_button;
  reg [24-1:0] M_test_io_dip;
  testerFSM_2 test (
    .clk(clk),
    .rst(rst),
    .io_button(M_test_io_button),
    .io_dip(M_test_io_dip),
    .r_op1(M_test_r_op1),
    .r_op2(M_test_r_op2),
    .out(M_test_out),
    .zOut(M_test_zOut),
    .vOut(M_test_vOut),
    .nOut(M_test_nOut),
    .text(M_test_text)
  );
  wire [8-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [28-1:0] M_seg_values;
  multi_seven_seg_3 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_test_io_dip = io_dip;
    M_test_io_button = io_button;
    io_led[0+7-:8] = M_test_out;
    io_led[8+7-:8] = M_test_r_op1;
    io_led[16+7-:8] = M_test_r_op2;
    led[0+0-:1] = M_test_zOut;
    led[1+0-:1] = M_test_vOut;
    led[2+0-:1] = M_test_nOut;
    M_seg_values = M_test_text;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
  end
endmodule
