/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_6 (
    input [7:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'hbf;
      end
      1'h1: begin
        segs = 8'h06;
      end
      2'h2: begin
        segs = 8'hdb;
      end
      2'h3: begin
        segs = 8'h4f;
      end
      3'h4: begin
        segs = 8'h66;
      end
      3'h5: begin
        segs = 8'h6d;
      end
      3'h6: begin
        segs = 8'hfd;
      end
      3'h7: begin
        segs = 8'h07;
      end
      4'h8: begin
        segs = 8'hff;
      end
      4'h9: begin
        segs = 8'h67;
      end
      7'h7a: begin
        segs = 8'h40;
      end
      7'h61: begin
        segs = 8'hf7;
      end
      7'h62: begin
        segs = 8'hfc;
      end
      7'h63: begin
        segs = 8'hb9;
      end
      7'h64: begin
        segs = 8'hde;
      end
      7'h65: begin
        segs = 8'hf9;
      end
      7'h66: begin
        segs = 8'hf1;
      end
      7'h68: begin
        segs = 8'hf4;
      end
      7'h6e: begin
        segs = 8'hd4;
      end
      7'h6c: begin
        segs = 8'h38;
      end
      7'h6f: begin
        segs = 8'hbf;
      end
      7'h70: begin
        segs = 8'hf3;
      end
      7'h72: begin
        segs = 8'hd0;
      end
      7'h73: begin
        segs = 8'h6d;
      end
      7'h74: begin
        segs = 8'h46;
      end
      7'h75: begin
        segs = 8'hbe;
      end
      7'h78: begin
        segs = 8'hf6;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
