/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_5 (
    input clk,
    input rst,
    input [5:0] alufn,
    input [7:0] op1,
    input [4:0] op2,
    output reg out
  );
  
  
  
  always @* begin
    out = 8'bxxxxxxxx;
    
    case (alufn)
      6'h20: begin
        out = op1 << op2;
      end
      6'h21: begin
        out = op1 >> op2;
      end
      6'h23: begin
        out = $signed(op1) >>> op2;
      end
    endcase
  end
endmodule
